name: main

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    uses: ./.github/workflows/lint-test.yaml

  fixup-commit-blocker:
    if: github.ref != 'refs/heads/main'
    uses: python-discord/.github/.github/workflows/block-fixup-commits.yaml@main
    needs: lint-test

  docs:
    uses: ./.github/workflows/docs.yaml
